/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLQuerySmuapi.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   smuapi/1.5
// Description:
//   Social mashup API
// Classes:
//   GTLQuerySmuapi (8 custom class methods, 12 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@interface GTLQuerySmuapi : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (copy) NSString *identifier;
@property (copy) NSString *message;
@property (assign) NSInteger numPage;
@property (copy) NSString *postId;
@property (assign) NSInteger sizePage;
@property (copy) NSString *tags;
@property (copy) NSString *to;
@property (copy) NSString *tokenFb;
@property (copy) NSString *tokenTw1;
@property (copy) NSString *tokenTw2;
@property (copy) NSString *type;

#pragma mark -
#pragma mark Service level methods
// These create a GTLQuerySmuapi object.

// Method: smuapi.deletePost
//  Optional:
//   tokenFb: NSString
//   tokenTw1: NSString
//   tokenTw2: NSString
//  Authorization scope(s):
//   kGTLAuthScopeSmuapiUserinfoEmail
+ (id)queryForDeletePostWithPostId:(NSString *)postId;

// Method: smuapi.getAllFriends
//  Optional:
//   tokenFb: NSString
//   tokenTw1: NSString
//   tokenTw2: NSString
//  Authorization scope(s):
//   kGTLAuthScopeSmuapiUserinfoEmail
// Fetches a GTLSmuapiUtenteCollection.
+ (id)queryForGetAllFriends;

// Method: smuapi.getHomePage
//  Optional:
//   tokenFb: NSString
//   tokenTw1: NSString
//   tokenTw2: NSString
//  Authorization scope(s):
//   kGTLAuthScopeSmuapiUserinfoEmail
// Fetches a GTLSmuapiSocialMessaggioCollection.
+ (id)queryForGetHomePageWithNumPage:(NSInteger)numPage
                            sizePage:(NSInteger)sizePage;

// Method: smuapi.like
//  Optional:
//   identifier: NSString
//   tokenFb: NSString
//   tokenTw1: NSString
//   tokenTw2: NSString
//   type: NSString
//  Authorization scope(s):
//   kGTLAuthScopeSmuapiUserinfoEmail
+ (id)queryForLikeWithTo:(NSString *)to;

// Method: smuapi.postComment
//  Optional:
//   tokenFb: NSString
//   tokenTw1: NSString
//   tokenTw2: NSString
//  Authorization scope(s):
//   kGTLAuthScopeSmuapiUserinfoEmail
+ (id)queryForPostCommentWithIdentifier:(NSString *)identifier
                                message:(NSString *)message
                                     to:(NSString *)to
                                   type:(NSString *)type;

// Method: smuapi.postStatus
//  Optional:
//   tags: NSString
//   tokenFb: NSString
//   tokenTw1: NSString
//   tokenTw2: NSString
//  Authorization scope(s):
//   kGTLAuthScopeSmuapiUserinfoEmail
+ (id)queryForPostStatusWithMessage:(NSString *)message
                                 to:(NSString *)to;

// Method: smuapi.retrieveMessage
//  Optional:
//   tokenFb: NSString
//   tokenTw1: NSString
//   tokenTw2: NSString
//  Authorization scope(s):
//   kGTLAuthScopeSmuapiUserinfoEmail
// Fetches a GTLSmuapiSocialMessaggioCollection.
+ (id)queryForRetrieveMessage;

// Method: smuapi.savePost
//  Optional:
//   tokenFb: NSString
//   tokenTw1: NSString
//   tokenTw2: NSString
//  Authorization scope(s):
//   kGTLAuthScopeSmuapiUserinfoEmail
+ (id)queryForSavePostWithNumPage:(NSInteger)numPage
                           postId:(NSString *)postId
                         sizePage:(NSInteger)sizePage;

@end
