/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLQuerySmuapi.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   smuapi/1.5
// Description:
//   Social mashup API
// Classes:
//   GTLQuerySmuapi (8 custom class methods, 12 custom properties)

#import "GTLQuerySmuapi.h"

#import "GTLSmuapiSocialMessaggioCollection.h"
#import "GTLSmuapiUtenteCollection.h"

@implementation GTLQuerySmuapi

@dynamic fields, identifier, message, numPage, postId, sizePage, tags, to,
         tokenFb, tokenTw1, tokenTw2, type;

+ (NSDictionary *)parameterNameMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

#pragma mark -
#pragma mark Service level methods
// These create a GTLQuerySmuapi object.

+ (id)queryForDeletePostWithPostId:(NSString *)postId {
  NSString *methodName = @"smuapi.deletePost";
  GTLQuerySmuapi *query = [self queryWithMethodName:methodName];
  query.postId = postId;
  return query;
}

+ (id)queryForGetAllFriends {
  NSString *methodName = @"smuapi.getAllFriends";
  GTLQuerySmuapi *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLSmuapiUtenteCollection class];
  return query;
}

+ (id)queryForGetHomePageWithNumPage:(NSInteger)numPage
                            sizePage:(NSInteger)sizePage {
  NSString *methodName = @"smuapi.getHomePage";
  GTLQuerySmuapi *query = [self queryWithMethodName:methodName];
  query.numPage = numPage;
  query.sizePage = sizePage;
  query.expectedObjectClass = [GTLSmuapiSocialMessaggioCollection class];
  return query;
}

+ (id)queryForLikeWithTo:(NSString *)to {
  NSString *methodName = @"smuapi.like";
  GTLQuerySmuapi *query = [self queryWithMethodName:methodName];
  query.to = to;
  return query;
}

+ (id)queryForPostCommentWithIdentifier:(NSString *)identifier
                                message:(NSString *)message
                                     to:(NSString *)to
                                   type:(NSString *)type {
  NSString *methodName = @"smuapi.postComment";
  GTLQuerySmuapi *query = [self queryWithMethodName:methodName];
  query.identifier = identifier;
  query.message = message;
  query.to = to;
  query.type = type;
  return query;
}

+ (id)queryForPostStatusWithMessage:(NSString *)message
                                 to:(NSString *)to {
  NSString *methodName = @"smuapi.postStatus";
  GTLQuerySmuapi *query = [self queryWithMethodName:methodName];
  query.message = message;
  query.to = to;
  return query;
}

+ (id)queryForRetrieveMessage {
  NSString *methodName = @"smuapi.retrieveMessage";
  GTLQuerySmuapi *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLSmuapiSocialMessaggioCollection class];
  return query;
}

+ (id)queryForSavePostWithNumPage:(NSInteger)numPage
                           postId:(NSString *)postId
                         sizePage:(NSInteger)sizePage {
  NSString *methodName = @"smuapi.savePost";
  GTLQuerySmuapi *query = [self queryWithMethodName:methodName];
  query.numPage = numPage;
  query.postId = postId;
  query.sizePage = sizePage;
  return query;
}

@end
