/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLSmuapiSocialMessaggio.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   smuapi/1.5
// Description:
//   Social mashup API
// Classes:
//   GTLSmuapiSocialMessaggio (0 custom class methods, 15 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLSmuapiSocialCommento;

// ----------------------------------------------------------------------------
//
//   GTLSmuapiSocialMessaggio
//

@interface GTLSmuapiSocialMessaggio : GTLObject
@property (copy) NSString *action;
@property (copy) NSString *caption;
@property (retain) NSNumber *comment;  // intValue
@property (retain) NSArray *commenti;  // of GTLSmuapiSocialCommento
@property (retain) GTLDateTime *createAt;
@property (copy) NSString *from;

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (copy) NSString *identifier;

@property (retain) NSNumber *like;  // intValue
@property (copy) NSString *link;
@property (copy) NSString *photo;
@property (retain) NSNumber *resend;  // intValue
@property (copy) NSString *text;
@property (copy) NSString *type;
@property (copy) NSString *user;
@property (retain) NSNumber *valid;  // boolValue
@end
