/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLSmuapi.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   smuapi/1.5
// Description:
//   Social mashup API

#import "GTLSmuapiConstants.h"

#import "GTLSmuapiSocialCommento.h"
#import "GTLSmuapiSocialMessaggio.h"
#import "GTLSmuapiSocialMessaggioCollection.h"
#import "GTLSmuapiUtente.h"
#import "GTLSmuapiUtenteCollection.h"

#import "GTLQuerySmuapi.h"
#import "GTLServiceSmuapi.h"
