/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLSmuapiUtenteCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   smuapi/1.5
// Description:
//   Social mashup API
// Classes:
//   GTLSmuapiUtenteCollection (0 custom class methods, 1 custom properties)

#import "GTLSmuapiUtenteCollection.h"

#import "GTLSmuapiUtente.h"

// ----------------------------------------------------------------------------
//
//   GTLSmuapiUtenteCollection
//

@implementation GTLSmuapiUtenteCollection
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLSmuapiUtente class]
                                forKey:@"items"];
  return map;
}

@end
