/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLSmuapiUtente.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   smuapi/1.5
// Description:
//   Social mashup API
// Classes:
//   GTLSmuapiUtente (0 custom class methods, 2 custom properties)

#import "GTLSmuapiUtente.h"

// ----------------------------------------------------------------------------
//
//   GTLSmuapiUtente
//

@implementation GTLSmuapiUtente
@dynamic identifier, nickname;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

@end
