/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLSmuapiSocialMessaggioCollection.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   smuapi/1.5
// Description:
//   Social mashup API
// Classes:
//   GTLSmuapiSocialMessaggioCollection (0 custom class methods, 1 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLSmuapiSocialMessaggio;

// ----------------------------------------------------------------------------
//
//   GTLSmuapiSocialMessaggioCollection
//

// This class supports NSFastEnumeration over its "items" property. It also
// supports -itemAtIndex: to retrieve individual objects from "items".

@interface GTLSmuapiSocialMessaggioCollection : GTLCollectionObject
@property (retain) NSArray *items;  // of GTLSmuapiSocialMessaggio
@end
