/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLSmuapiConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   smuapi/1.5
// Description:
//   Social mashup API

#import "GTLSmuapiConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeSmuapiUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
